# -*- coding: utf-8 -*-
"""Python mini Projects

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qXmSl1iK4IxCzFOvR9RzTbzK5jgLh-AX
"""

print("Hello, and welcome to the Python Mini Projects... ")
user=(input("Please enter your name:   "))

if user == "Shania":
   print("Hello Shania! ")

elif user != "Shania":
    print("Welcome guest")

print("Have fun!")

#simple calculator
num1=int(input("Enter num1:"))  #get first number from user 
num2=int(input("Enter num2:"))  #get secound number from user 
action= str(input("Choose an action: Add(a), Sub(s), Multi(m), Div (d)->")) #ask the user to pick an action 

print("The result is ", end="")
if action=="a":
   print(num1+num2)     #add    
elif action == "s":
     print(num1-num2)   #subtract 
elif action =="m":
      print(num1*num2)  #multiply 
else: 
  print(num1/num2)      #divide

#random password generator 
import random  #import random lib

lower="abcdefghijklmnopqrstuvwxyz"  
upper="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
number="0123456789"
symbols="[]{}%*_-"

all= lower+upper+number+symbols
length=6  #password length

password="".join(random.sample(all,length))
print(password)   #print password

#check if number is positive 
num=float(input("Enter a number:   ")) #ask user to put in a number 
if num>= 0:
    if num == 0:
      print("Zero")
    else:
      print("Positive number")
else:
    print("Negative number")

#guess the number game 
import random
number=random.randint(1,10)
for i in range(0,3):
     user = int(input("Guess the number:   "))
     if user== number:
       print("Yeah!!")
       print(f"The number is {number}")
       break

if user != number:
  print(f"You guess is incorrect. The number is {number}")

#text based adventure 
name= str(input("Enter your name\n")) #get the users name 
print(f" {name}, You are stuck in the forest. Your task is to get out of the forest without dieing")
print("you are walking through the forest when a dragon comes out of the sky. Now there are only four options.") #format the story
print("1.RUN! 2.CLIMB INTO A TREE NEARBY! 3.KILL THE DRAGON! 4. YOU SEE A WIZARD AND ASK FOR A POTION!") #user's choice 
user= int(input("choose option 1, 2 , 3 , or 4 "))  #options 


if user == 1:
     print("You Died!")
elif user == 2:
     print("You survived!!")
elif user == 3:
    print("You are injured...so you die!")
elif user == 4: 
     print("The wizard gives you a potion...it turns you into a Dragon! You win the dragon fight and survived!")
else: 
  print("Incorrect input, please try again")

place= str(input("enter a place\n"))
print(f" Now in {place}, finally you made it out of the forest, Your task is to help the knight find the dragons layer without dieing")
print("you have found the dragons layer! Now there are only two options")
print("1. GO INSIDE 2. STAY OUT SIDE")
user= int(input("choose option 1 or 2"))

if user == 1: 
  print(" You go inside and find the dragon asleep, you sneak past and find the tresure! The adventure is now over.")
elif user == 2:
     print(" You stayed out side too long... another dragon comes a along and eats you! You died!")

#Mad Libs Generator 
color= input("Enter a color:  ")
pluralNoun = input("Enter a plural noun:  ")
celebrity= input("Enter a celebrity:   ")
print("Roses are", color )
print(pluralNoun + " are blue")
print("I love", celebrity)

#story generator